version: '3.9'
services:
  dev-db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: development
      POSTGRES_DB: nest
    networks:
      - development
networks:
  development:
